### PR TITLE
Update indexlr

### PR DESCRIPTION
**Pull request by schutzekatze**
Updated indexlr with `--long` mode for optimized CPU/memory for long sequences. Also updated btllib to latest.

### CODE REVIEW

**Comment by schutzekatze** [comment]
Python package installation failed in CI for some reason. The PR doesn't touch those files, though.

**Comment by lcoombe** [comment]
Ahh yes, I saw this in my branch and fixed it there - it was due to updates in linuxbrew. I just merged those changes in master, so it should be fixed if you rebase your branch on master

**Comment by schutzekatze** [comment]
Done.

**Review by lcoombe — APPROVED** [review]

**Comment by lcoombe** [comment]
Thanks Vlad!

**Pull request merged**
