### PR TITLE
btllib port of indexlr

### PR DESCRIPTION
**Pull request by schutzekatze**
Performance seems almost the same for both short and long reads, but the new indexlr gets away with using less CPU and memory.

Short reads (/projects/btl/datasets/hsapiens/giab/HG004/D3_S1_L002_011.fq.gz), 3 tests for both indexlrs:
|  | Time (mm:ss) | Max mem usage | CPU % used |
| --------------- | --------------- | --------------- | --------------- |
| old indexlr | 1:05 | 443MiB | 573% |
|  | 1:01 | 436MiB | 599% |
|  | 1:00 | 438MiB | 609% |
| new indexlr | 0:56 | 197MB | 456% |
|  | 0:54 | 199MB | 467% |
|  | 0:52 | 199MB | 479% |

Long reads (/projects/btl_scratch/hackathons/october2020/long_read_assembly/data/hsapiens/NA19240/NA19240.ont.chr20.fq.gz), 3 tests for both indexlrs:
|  | Time (mm:ss) | Max mem usage | CPU % used |
| --------------- | --------------- | --------------- | --------------- |
| old indexlr | 5:05 | 31GiB | 536% |
|  | 5:13 | 31GiB | 519% |
|  | 5:05 | 31GiB | 530% |
| new indexlr | 4:54 | 10GiB | 289% |
|  | 5:06 | 10GiB | 283% |
|  | 4:57 | 9GiB | 290% |          

More importantly, though, it seems that old indexlr had a bug where it skipped a few reads in its output that should've outputted minimizers. The number of these is very small, but it's been fixed in the new indexlr.

There's a large number of files introduced, but that's because btllib was added and all the changes are constrained to the src/ dir.

### CODE REVIEW

**Comment by schutzekatze** [comment]
@lcoombe It seems pylint is failing, unrelated to this PR. Could it be because of some pylint update?

**Comment by lcoombe** [comment]
Sigh... Yeah I've seen this before when pylint updates - I'll fix the pylint error in a separate PR and then you could rebase this branch on the new master when I'm done merging that one?

**Comment by lcoombe** [comment]
Ok, try rebasing the branch on the current master -- the pylint error should be fixed in master now.

**Comment by lcoombe** [comment]
Thanks Vlad!

**Pull request merged**
